### ISSUE TITLE
Visual Studio 2017 version 15.7 no longer works

### ISSUE THREAD

**Issue by Cerlancism** [Art-Stea1th/Enhanced-Syntax-Highlighting#11]
Many tags such as methods, extension methods and local variables colors stopped working.

**Comment by 0Petya** [comment]
Can confirm that this is happening.

**Comment by Cassiobsk8** [comment]
Can confirm, the extension is loaded properly and is showing the user tags config but is not coloring.
tested in 15.7 and 15.7.1.

**Comment by Art-Stea1th** [comment]
Hi all, yes, I already know about this issue, by the end of this working week I will try to look and understand what's wrong. Also, I will be very grateful for any help the community in this issue.

**Comment by Spaier** [comment]
Found and fixed the issue. I will make a pull request later. In Visual Studio 2017 15.7 Property names, method names and etc. have ClassificationType `"property name"`, `"method name"` and etc., not `"identifier"` while current code uses `Convert` method only for `s.ClassificationType == "identifier"` so everything except Namespace identifiers is left out.
UPD: Created PR

**Comment by Art-Stea1th** [comment]
Hello, Spaier. Thank you for finding the reason. I wrote [here](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/pull/12).
