### ISSUE TITLE
Syntax highlighting for reserved words like (if, for, foreach, while, throw, return, etc.)

### ISSUE THREAD

**Issue by username1223121** [Art-Stea1th/Enhanced-Syntax-Highlighting#14]
I would like to recommend new syntax highlighting for specified reserved words. You can find whole syntax highlighting in Visual Studio Code. Here is the the sample attached. I believe this looks much cleaner with rose/purple color used for those reserved words, and i think code is easier to read.
![Annotation 2019-03-12 182011](https://user-images.githubusercontent.com/48490988/54223363-98a3e700-44f7-11e9-989d-582445e26e66.png)

**Comment by Spaier** [comment]
@username1223121 I recommend you to use Viasfora(https://marketplace.visualstudio.com/items?itemName=TomasRestrepo.Viasfora) with ESH. It highlights flow/linq keywords.

**Comment by Art-Stea1th** [comment]
Hello, username1223121.
This is a great idea, but all tag highlighting requests should be [there](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/7). Regards.
