### ISSUE TITLE
Add: syntax highlighting for other "User Tags - ...".

### ISSUE THREAD

**Issue by ryanwoodcox** [Art-Stea1th/Enhanced-Syntax-Highlighting#4]
Is there anyway to give us the ability to select a custom color for "constants"?

public const string IAmAConstant = "hello";

**Comment by Art-Stea1th** [comment]
Hello, Ryan.

In the early days of December, I will have a little more free time and I will be able to give a more accurate answer.

Regards.

**Comment by Art-Stea1th** [comment]
In the coming 1-2 days, it will be added the ability to change highlighting for:
- Enum Entries
- Events
- Fields (Constant)
- Methods (Extension)
- Methods (Static)

**Comment by Art-Stea1th** [comment]
updated:
[![v 1.1 build 6547 rev. 73](https://img.shields.io/badge/v%201.1%20build%206547%20rev.%2073-Latest-green.svg?style=flat-square&colorB=9FB861)](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/releases/tag/1.1.6547.73)

**Comment by Art-Stea1th** [comment]
Now a [special issue](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/7) has been created for these purposes.
