### ISSUE TITLE
Add: support for Visual Basic.

### ISSUE THREAD

**Issue by penCsharpener** [Art-Stea1th/Enhanced-Syntax-Highlighting#5]
Please add support for vb.NET

**Comment by Art-Stea1th** [comment]
Hello vbNETonIce, I can give you a more accurate answer after solving this issue:
- [Add highlighting for other "User Tags - ..."](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/4)

Please stay in touch. Regards.

**Comment by Art-Stea1th** [comment]
I think I'll add this feature with the next update.

**Comment by Art-Stea1th** [comment]
[![Visual Studio | Marketplace](https://img.shields.io/badge/Visual%20Studio%20%7C%20Marketplace-1.2-green.svg?style=flat-square&colorB=8631C7&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAYAAAByDd%2BUAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAgtJREFUeNq01s9LlEEcx3F3i1gUIkEsWJEiiZR2A0tJXIKuS5cW9GyE%2FgEZCOGC4MEfGB1ClD20Fy%2B6RURQQR4NikBBg06FINopjdZSWNun9%2BA8MD3OjM%2BzPg68Ls%2FM83yY7zwzzxNxHKcq5JbBLeSwcqBXBIboJtac%2FfYdeaQRc8eEHfbD0bdlDOFSJKSSpvAc9YeM%2BxQNIawDz3yEiXZKDYzjesCwdrzAWZ%2Fjy6L2UWTwDbvo97lmbVh3grVFceOgpuMpzljCWpW3MVCgKOl5zdTv4g2uaPquyjI2GMr2GdummorAkqHvBublRnZbUoY1Gu7Jowd7xlVkmlPKlMU6Fj1l%2BIsBWcavlnJNyHJfwG%2FbGqqBk%2BhGSTPY9JA93FfW9zK2TYEnPROOYQ418ixU%2B6s1BSriHgp%2B95F340eUteiVDzS1L0gHCdMFqk28MFuWfvE2LgQ9lkwzFFvlteVtFK0Lr1B3lMA%2FOIeXSPi4%2FzbeoqnSwIvyIE56rn%2FAuOEZ1%2FAOne5OsyZ6toWuzaJWvvIPLON%2Byo9tXLOX%2F9uH04bOkjxnvefogCV0B4%2BxaQvMaTo2cMdyeD88pCplW2ACBeXiezT7%2BDxlK%2FlaqA%2FowxOcDvAfM3SUwEoNBwhcCuOfJotRn2NPhPmbOGaZ2S%2FMIBX2j%2FCEJ2gVI2g5jh9h1yN8RC%2FqvP3%2FBBgAP9DoY%2BErIbwAAAAASUVORK5CYII%3D)](https://marketplace.visualstudio.com/items?itemName=StanislavKuzmichArtStea1th.EnhancedSyntaxHighlighting) [![v 1.2 build 6547 rev. 73](https://img.shields.io/badge/v%201.2%20build%206551%20rev.%2038038-Latest-green.svg?style=flat-square&colorB=9FB861)](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/releases/tag/1.2.6551.38038)
[![Visual Studio 2017](https://img.shields.io/badge/Visual%20Studio-2017-green.svg?style=flat-square&colorB=8631C7)](https://marketplace.visualstudio.com/items?itemName=StanislavKuzmichArtStea1th.EnhancedSyntaxHighlighting) [![Visual Studio 2015](https://img.shields.io/badge/Visual%20Studio-2015-green.svg?style=flat-square&colorB=8631C7)](https://marketplace.visualstudio.com/items?itemName=StanislavKuzmichArtStea1th.EnhancedSyntaxHighlighting) [![Highlighting for C#](https://img.shields.io/badge/Highlighting%20for%3A-C%23-green.svg?style=flat-square&colorB=9FB861)](#) [![Highlighting for Visual Basic](https://img.shields.io/badge/Highlighting%20for%3A-Visual%20Basic-blue.svg?style=flat-square&colorB=4A90CE)](#)
