### ISSUE TITLE
Add: syntax highlighting for Static Classes.

### ISSUE THREAD

**Issue by ryanwoodcox** [Art-Stea1th/Enhanced-Syntax-Highlighting#6]
Could you add support for Static Classes much like you did with Static and Extension Methods in the last update?

Thanks!

**Comment by Art-Stea1th** [comment]
Hello again, Ryan.

To add **syntax highlighting** for "**extension methods**", "**static methods**", "**constants**" and other "syntactic units", requests were received not only [from you](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/4), but also [from others](https://marketplace.visualstudio.com/items?itemName=StanislavKuzmichArtStea1th.EnhancedSyntaxHighlighting) directly on the Visual Studio Marketplace.

Now I created an [issue](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/7) special for these purposes. Could you [read it please](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/7) and [place your request there](https://github.com/Art-Stea1th/Enhanced-Syntax-Highlighting/issues/7). Perhaps I will consider what you asked for.

Thank you for understanding. Regards.
